
defaults: &defaults
  google_maps_key: AIzaSyDZskm7m07DuLiu6U-f1345jXdBwLRClW4
  insertion_filter_url: <YOUR FINN QUERY HERE, EXAMPLE - http://www.finn.no/finn/realestate/lettings/result?PRICE_FROM=&sort=1&ESTATE_SIZE/LIVING_AREA_FROM=75&areaId=20061&PRICE_TO=17000&ESTATE_SIZE/LIVING_AREA_TO=&NUMBER_OF_BEDROOMS_FROM=2&NUMBER_OF_BEDROOMS_TO=2>
  insertion_notification_threshold: 5
  twilio_account_sid:  <YOUR TWILIO ACCOUNT SID>
  twilio_auth_token: <YOUR TWILIO ACCOUNT TOKEN>
  twilio_source_number: <YOUR TWILIO SOURCE NUMBER, WITH COUNTRY CODE, WITH SINGLE QUOTES, EXAMPLE '+1555404040'>
  twilio_target_number: <YOUR TWILIO TARGET NUMBER, WITH COUNTRY CODE, WITH SINGLE QUOTES, EXAMPLE '+47911200303'>

development:
  <<: *defaults

production:
  <<: *defaults
